// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-Y2o7ulQJzvQ72diapG9k7gHatTGvYJ0',
    appId: '1:642219133476:web:eeff9037cd766beb82a6b1',
    messagingSenderId: '642219133476',
    projectId: 'turf-mate-18a2b',
    authDomain: 'turf-mate-18a2b.firebaseapp.com',
    storageBucket: 'turf-mate-18a2b.firebasestorage.app',
    measurementId: 'G-PJD761PNCJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAl0qsMFQRjAAMxI9CK8-ehBO8Dm9OgJvo',
    appId: '1:642219133476:android:6e386d1b956b748782a6b1',
    messagingSenderId: '642219133476',
    projectId: 'turf-mate-18a2b',
    storageBucket: 'turf-mate-18a2b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBjFIB82gIKQpAMFGfadSejxJihmK0OTNE',
    appId: '1:642219133476:ios:89a4394ecb8c2d2382a6b1',
    messagingSenderId: '642219133476',
    projectId: 'turf-mate-18a2b',
    storageBucket: 'turf-mate-18a2b.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );
}
